In [1]:
import numpy as np

In [2]:
np.array([3,4,6,7,3,5])

array([3, 4, 6, 7, 3, 5])

In [3]:
np.array([[3,4,6],[2,3,6],[2,3,6],[6,8,9],[2,4,6]])

array([[3, 4, 6],
       [2, 3, 6],
       [2, 3, 6],
       [6, 8, 9],
       [2, 4, 6]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [10]:
# it returns 50 elements within a range with equal interval
np.linspace(1,25,retstep=True, num=20)

(array([ 1.        ,  2.26315789,  3.52631579,  4.78947368,  6.05263158,
         7.31578947,  8.57894737,  9.84210526, 11.10526316, 12.36842105,
        13.63157895, 14.89473684, 16.15789474, 17.42105263, 18.68421053,
        19.94736842, 21.21052632, 22.47368421, 23.73684211, 25.        ]),
 1.263157894736842)

In [12]:
# will generate random number between 0 and 1
np.random.random()

0.38645400301748967

In [13]:
np.random.random([4,5])

array([[0.62194999, 0.25840472, 0.06833158, 0.82115209, 0.37131699],
       [0.15255262, 0.17719057, 0.72380717, 0.52051706, 0.39503984],
       [0.40992347, 0.01543574, 0.95018678, 0.3506675 , 0.23003715],
       [0.62631672, 0.79149691, 0.50564436, 0.12441578, 0.00335414]])

In [14]:
np.random.randint(1,100)

76

In [15]:
np.random.randint(1,100,20)

array([85, 18,  2, 43, 36, 27, 82, 81, 90, 34, 62, 51, 84, 73, 23,  6,  1,
       77, 54, 41])

In [16]:
np.random.randint(1,100,[4,6])

array([[67, 70, 54, 75,  6, 31],
       [38, 40, 19, 91, 54, 50],
       [89, 81, 90, 34, 73, 97],
       [58, 17, 81, 65, 11, 85]])

In [17]:
x = np.random.randint(1,100,10)

In [18]:
x

array([89, 56, 25,  2, 14, 86,  3, 89, 60, 60])

In [19]:
x[0]

89

In [20]:
x[-1]

60

In [21]:
x[0:5]

array([89, 56, 25,  2, 14])

In [22]:
np.mean(x)

48.4

In [23]:
np.median(x)

58.0

In [24]:
np.sum(x)

484

In [25]:
np.min(x)

2

In [26]:
np.max(x)

89

In [27]:
x

array([89, 56, 25,  2, 14, 86,  3, 89, 60, 60])

In [28]:
np.argmin(x)

3

In [29]:
np.sort(x)

array([ 2,  3, 14, 25, 56, 60, 60, 86, 89, 89])

In [30]:
x = np.random.randint(1,100,24)

In [31]:
x

array([40, 10, 77, 20, 91, 22, 14, 38, 11, 25, 57, 53, 46, 86, 50, 33, 34,
       58, 12, 24,  8, 50, 26, 11])

In [32]:
x = np.reshape(x, (4,6))

In [33]:
x

array([[40, 10, 77, 20, 91, 22],
       [14, 38, 11, 25, 57, 53],
       [46, 86, 50, 33, 34, 58],
       [12, 24,  8, 50, 26, 11]])

In [34]:
x.shape

(4, 6)

In [35]:
np.max(x)

91

In [36]:
# maximum value of each column
np.max(x, axis=0)

array([46, 86, 77, 50, 91, 58])

In [37]:
# maximum value of each row
np.max(x, axis=1)

array([91, 57, 86, 50])

In [38]:
np.mean(x)

37.333333333333336

In [39]:
np.mean(x, axis=0)

array([28. , 39.5, 36.5, 32. , 52. , 36. ])

In [40]:
x

array([[40, 10, 77, 20, 91, 22],
       [14, 38, 11, 25, 57, 53],
       [46, 86, 50, 33, 34, 58],
       [12, 24,  8, 50, 26, 11]])

In [41]:
x[0]

array([40, 10, 77, 20, 91, 22])

In [42]:
x[0][0]

40

In [43]:
x[0][1]

10

In [44]:
# x[: - get all rows, ]
x[:,1]

array([10, 38, 86, 24])

In [45]:
x[:, 0:3]

array([[40, 10, 77],
       [14, 38, 11],
       [46, 86, 50],
       [12, 24,  8]])

In [46]:
x[:, [0,2,4]]

array([[40, 77, 91],
       [14, 11, 57],
       [46, 50, 34],
       [12,  8, 26]])

In [47]:
import pandas as pd

In [49]:
series = pd.Series(x.flatten())

In [51]:
# returns first 5 observations by default
series.head()

0    40
1    10
2    77
3    20
4    91
dtype: int64

In [52]:
# returns last 5 observations by default
series.tail()

19    24
20     8
21    50
22    26
23    11
dtype: int64

In [55]:
series.sort_values(ascending=False).head()

4     91
13    86
2     77
17    58
10    57
dtype: int64

In [57]:
series.sort_values(ascending=False).head().reset_index(drop=True)

0    91
1    86
2    77
3    58
4    57
dtype: int64

In [58]:
series[0:5]

0    40
1    10
2    77
3    20
4    91
dtype: int64

In [59]:
data = {
    "names" : ["John","Smith","Mac","Sam","Nick","John","Tom","Matt"],
    "dept" : ["IT","HR","IT","IT","Sales","Admin","IT","Sales"],
    "salary" : [45000,50000,35000,55000,25000,76000,80000,35000]
}

In [60]:
pd.Series(data)

names        [John, Smith, Mac, Sam, Nick, John, Tom, Matt]
dept              [IT, HR, IT, IT, Sales, Admin, IT, Sales]
salary    [45000, 50000, 35000, 55000, 25000, 76000, 800...
dtype: object

In [61]:
df = pd.DataFrame(data)

In [64]:
df.head(3)

names dept  salary
0   John   IT   45000
1  Smith   HR   50000
2    Mac   IT   35000

In [65]:
df.tail(3)

names   dept  salary
5  John  Admin   76000
6   Tom     IT   80000
7  Matt  Sales   35000

In [67]:
df['names'].head()

0     John
1    Smith
2      Mac
3      Sam
4     Nick
Name: names, dtype: object

In [69]:
df.names.head()

0     John
1    Smith
2      Mac
3      Sam
4     Nick
Name: names, dtype: object

In [72]:
df[['names','salary']].head(4)

names  salary
0   John   45000
1  Smith   50000
2    Mac   35000
3    Sam   55000

In [73]:
df['dept'] == 'IT'

0     True
1    False
2     True
3     True
4    False
5    False
6     True
7    False
Name: dept, dtype: bool

In [74]:
df[df['dept'] == 'IT']

names dept  salary
0  John   IT   45000
2   Mac   IT   35000
3   Sam   IT   55000
6   Tom   IT   80000

In [76]:
df[df['salary'] > 60000]

names   dept  salary
5  John  Admin   76000
6   Tom     IT   80000

In [78]:
df[(df['salary'] > 60000) & (df['dept'] == 'IT')]

names dept  salary
6   Tom   IT   80000

In [80]:
df.iloc[0]

names      John
dept         IT
salary    45000
Name: 0, dtype: object

In [81]:
df.iloc[0:3]

names dept  salary
0   John   IT   45000
1  Smith   HR   50000
2    Mac   IT   35000

In [82]:
pd.value_counts(df['dept'])

IT       4
Sales    2
HR       1
Admin    1
Name: dept, dtype: int64