In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [23]:
df = pd.read_csv('Madedata1.csv')

In [24]:
df.head()

Country  Age  ... Contact_with_covid_patient  Infected
0               China   10  ...                         No         0
1               Italy   20  ...                  Not known         1
2                Iran   55  ...                         No         0
3  Republic of Korean   37  ...                        Yes         1
4              France   45  ...                        Yes         1

[5 rows x 12 columns]

In [25]:
df = df.drop(columns=['Country'])

In [26]:
pd.value_counts(df['Gender'])

Male           1257
Female         1208
Transgender      34
Name: Gender, dtype: int64

In [27]:
pd.value_counts(df['Severity'])

Mild        1591
Moderate     525
Severe       383
Name: Severity, dtype: int64

In [28]:
pd.value_counts(df['Contact_with_covid_patient'])

No           1203
Yes           638
Not known     633
yes            25
Name: Contact_with_covid_patient, dtype: int64

In [29]:
df['Contact_with_covid_patient'] = df['Contact_with_covid_patient'].str.lower()

In [30]:
pd.value_counts(df['Contact_with_covid_patient'])

no           1203
yes           663
not known     633
Name: Contact_with_covid_patient, dtype: int64

In [31]:
genderlabel = LabelEncoder()
gender = genderlabel.fit_transform(df['Gender'])

In [32]:
pd.value_counts(gender)

1    1257
0    1208
2      34
dtype: int64

In [33]:
severitylabel = LabelEncoder()
severity = severitylabel.fit_transform(df['Severity'])

In [34]:
contactlabel = LabelEncoder()
contact = contactlabel.fit_transform(df['Contact_with_covid_patient'])

In [35]:
df = df.drop(columns=['Gender','Contact_with_covid_patient','Severity'])

In [36]:
df.head()

Age  fever  Bodypain  ...  Nasal_congestion  Sore_throat  Infected
0   10    102         1  ...                 0            1         0
1   20    103         1  ...                 0            0         1
2   55     99         0  ...                 1            1         0
3   37    100         0  ...                 0            0         1
4   45    101         1  ...                 1            0         1

[5 rows x 8 columns]

In [37]:
gender = np.reshape(gender, (-1,1))
genderonehot = OneHotEncoder()
gender = genderonehot.fit_transform(gender).toarray()

In [38]:
gender

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [40]:
severity = np.reshape(severity, (-1,1))
severityonehot = OneHotEncoder()
severity = severityonehot.fit_transform(severity).toarray()

In [41]:
severity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])

In [42]:
contact = np.reshape(contact, (-1,1))
contactonehot = OneHotEncoder()
contact = contactonehot.fit_transform(contact).toarray()

In [43]:
contact

array([[1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
X = df.iloc[:,:-1].values

In [48]:
X = np.c_[X, gender, severity, contact]

In [49]:
X[0]

array([ 10., 102.,   1.,   0.,   0.,   0.,   1.,   0.,   1.,   0.,   1.,
         0.,   0.,   1.,   0.,   0.])

In [50]:
y = df.iloc[:, -1].values

In [51]:
minmax = MinMaxScaler()
X = minmax.fit_transform(X)

In [52]:
X[0]

array([0.        , 0.66666667, 1.        , 0.        , 0.        ,
       0.        , 1.        , 0.        , 1.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        ])

In [53]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [54]:
X.shape

(2499, 16)

In [55]:
x_train.shape

(1874, 16)

In [56]:
logistic = LogisticRegression()
logistic.fit(x_train, y_train)

LogisticRegression()

In [57]:
y_pred = logistic.predict(x_test)

In [58]:
accuracy_score(y_test, y_pred)

0.9424

In [59]:
confusion_matrix(y_test, y_pred)

array([[301,  21],
       [ 15, 288]])

In [60]:
y_test.shape

(625,)

In [61]:
301 + 288

589

In [62]:
21 + 15

36